apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name  }}
    heritage: {{ .Release.Service }}
  annotations:
    version: "{{ .Chart.Version }}"
data:
  config.cfg: |-
    DATABASE = 'luma_database.db'
    HOST = '0.0.0.0'
    PORT = 5000
    API_KEY = {{ .Values.lumaApiKey | quote }}
    SQLALCHEMY_TRACK_MODIFICATIONS = False
  generators.cfg: |-

    {{- if .Values.posix.enabled }}
    [posix]
    lowest_uid = {{ .Values.posix.lowest_uid }}
    highest_uid = {{ .Values.posix.highest_uid }}
    {{- end }}

    {{- if .Values.s3.enabled }}
    [s3]
    access_key = {{ .Values.s3.access_key }}
    secret_key = {{ .Values.s3.secret_key }}
    {{- end }}

    {{- if .Values.ceph.enabled }}
    [ceph]
    pool_name = {{ .Values.ceph.pool_name }}
    username = {{ .Values.ceph.username }}
    key = {{ .Values.ceph.key }}
    monitor_hostname = {{ template "volume-ceph_name" . }}
    {{- end }}

    {{- if .Values.swift.enabled }}
    [swift]
    username = {{ .Values.swift.username }}
    password = {{ .Values.swift.password }}
    {{- end }}
 
  generators_mapping.json: |-
    [
    {
        "storageType": "ceph",
        "generatorId": "ceph"
    },
    {
        "storageType": "posix",
        "generatorId": "posix"
    },
    {
        "storageType": "s3",
        "generatorId": "s3"
    },
    {
        "storageType": "swift",
        "generatorId": "swift"
    }
    ]