kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-sfs-pvc
  labels:
    type: sfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2500Gi
  storageClassName: ""
  selector:
    matchLabels:
      type: "sfs"
