apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    version: "{{ .Chart.Version }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 6789
      protocol: TCP
      targetPort: 6789
  selector:
    app: {{ template "fullname" . }}
  # TODO: The None option is specified to do not yet understood problems of communication with
  # CEPH server when forwarding traffic via service ip
  clusterIP: None
