apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "fullname" . }}-pv-sfs
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    type: sfs
  annotations:
    version: "{{ .Chart.Version }}"
    volume.beta.kubernetes.io/mount-options: {{ .Values.mount_options | quote }}
spec:
  capacity:
    storage: {{ .Values.storage | quote }}
  accessModes:
    - ReadWriteMany
  # The NFS server pod is deleted anyway so no need to recycle
  persistentVolumeReclaimPolicy: Retain
  nfs:
    # TODO: The NFS server name is resolved using nodes resolve.conf
    # here we expect that nodes resovle.conf can resolve namespaces service name
    # to FQDN k8s domain. But this is a special case, usually NFS servers are not
    # deployed ad-hoc :)
    server: "{{ .Values.server }}"
    path: "{{ .Values.path }}"
