apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    version: "{{ .Chart.Version }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    app: {{ template "fullname" . }}