name: onedata-1p
version: 0.2.7
description: Complex Onedata deployment with one Onezone, one Oneprovider and S3, CEPH, NFS, POSIX backends.
keywords:
  - onedata
  - onedata-meta-chart
home: https://www.onedata.org
sources:
  - https://github.com/onedata/onedata
maintainers:
  - name: Michal Orzechowski
    email: orzechowski.michal@gmail.com
engine: gotpl
appVersion: 17.06.0-beta6